all: SDLWedge1 SDLWedge2
	
SDLWedge1:
	g++  SDLWedge1.cpp  -o SDLWedge1 -lSDL2 -lSDL2_image -lSDL2_ttf
SDLWedge2:
	g++  SDLWedge2.cpp  -o SDLWedge2 -lSDL2 -lSDL2_image -lSDL2_ttf
clean:
	rm -rf *o SDLWedge1 SDLWedge2

